version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    container_name: judo-blog-app
    command: yarn dev
    ports:
      - 3000:3000

  db:
    image: postgres:16
    container_name: judo-blog-db
    environment:
      MYSQL_DATABASE: judo_blog
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: judo_blog
      MYSQL_PASSWORD: judo_blog
    volumes:
      - ./db/initial-data:/docker-entrypoint-initdb.d
