version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    working_dir: /app
    container_name: judo-blog-app
    command: yarn dev
    ports:
      - 3000:3000

  db:
    image: postgres:16
    container_name: judo-blog-db
    environment:
      POSTGRES_DB: judo_blog
      POSTGRES_USER: judo_blog
      POSTGRES_PASSWORD: judo_blog
    volumes:
      - ./db/initial-data:/docker-entrypoint-initdb.d
