import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { BlogLayout } from "@/components/ui/BlogLayout";
import { Provider } from "@/components/provider";

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={notoSans.className}>
                <Provider>
                    <BlogLayout>{children}</BlogLayout>
                </Provider>
            </body>
        </html>
    );
}
